# This workflow will build a Java project with Maven and upload the dependency graph
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# ✅ Give the workflow the permissions it needs
permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # ✅ Submit dependency graph to GitHub
      - name: Submit dependencies to GitHub
        uses: advanced-security/maven-dependency-submission-action@v4

      # ✅ Upload the built JAR as an artifact
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: my-java-app
          path: target/*.jar
